;GEOS System Jump Table
;reassembled by Maciej 'YTM/Alliance' Witkowiak
;4-2-99
 
;jump table
InterruptMain        equ    $c100
InitProcesses        equ    $c103
RestartProcess        equ    $c106
EnableProcess        equ    $c109
BlockProcess        equ    $c10c
UnBlockProcess        equ    $c10f
FreezeProcess        equ    $c112
UnFreezeProcess     equ    $c115
HorizontalLine        equ    $c118
InvertLine        equ    $c11b
RecoverLine        equ    $c11e
VerticalLine        equ    $c121
Rectangle        equ    $c124
FrameRectangle        equ    $c127
InvertRectangle     equ    $c12a
RecoverRectangle    equ    $c12d
DrawLine        equ    $c130
DrawPoint        equ    $c133
GraphicsString        equ    $c136
SetPattern        equ    $c139
GetScanLine        equ    $c13c
TestPoint        equ    $c13f
BitmapUp        equ    $c142
PutChar         equ    $c145
PutString        equ    $c148
UseSystemFont        equ    $c14b
StartMouseMode        equ    $c14e
DoMenu            equ    $c151
RecoverMenu        equ    $c154
RecoverAllMenus     equ    $c157
DoIcons         equ    $c15a
DShiftLeft        equ    $c15d
BBMult            equ    $c160
BMult            equ    $c163
DMult            equ    $c166
Ddiv            equ    $c169
DSdiv            equ    $c16c
Dabs            equ    $c16f
Dnegate         equ    $c172
Ddec            equ    $c175
ClearRam        equ    $c178
FillRam         equ    $c17b
MoveData        equ    $c17e
InitRam         equ    $c181
PutDecimal        equ    $c184
GetRandom        equ    $c187
MouseUp         equ    $c18a
MouseOff        equ    $c18d
DoPreviousMenu        equ    $c190
ReDoMenu        equ    $c193
GetSerialNumber     equ    $c196
Sleep            equ    $c199
ClearMouseMode        equ    $c19c
i_Rectangle        equ    $c19f
i_FrameRectangle    equ    $c1a2
i_RecoverRectangle    equ    $c1a5
i_GraphicsString    equ    $c1a8
i_BitmapUp        equ    $c1ab
i_PutString        equ    $c1ae
GetRealSize        equ    $c1b1
i_FillRam        equ    $c1b4
i_MoveData        equ    $c1b7
GetString        equ    $c1ba
GotoFirstMenu        equ    $c1bd
InitTextPrompt        equ    $c1c0
MainLoop        equ    $c1c3
DrawSprite        equ    $c1c6
GetCharWidth        equ    $c1c9
LoadCharSet        equ    $c1cc
PosSprite        equ    $c1cf
EnablSprite        equ    $c1d2
DisablSprite        equ    $c1d5
CallRoutine        equ    $c1d8
CalcBlksFree        equ    $c1db
ChkDkGEOS        equ    $c1de
NewDisk         equ    $c1e1
GetBlock        equ    $c1e4
PutBlock        equ    $c1e7
SetGEOSDisk        equ    $c1ea
SaveFile        equ    $c1ed
SetGDirEntry        equ    $c1f0
BldGDirEntry        equ    $c1f3
GetFreeDirBlk        equ    $c1f6
WriteFile        equ    $c1f9
BlkAlloc        equ    $c1fc
ReadFile        equ    $c1ff
SmallPutChar        equ    $c202
FollowChain        equ    $c205
GetFile         equ    $c208
FindFile        equ    $c20b
CRC            equ    $c20e
LdFile            equ    $c211
EnterTurbo        equ    $c214
LdDeskAcc        equ    $c217
ReadBlock        equ    $c21a
LdApplic        equ    $c21d
WriteBlock        equ    $c220
VerWriteBlock        equ    $c223
FreeFile        equ    $c226
GetFHdrInfo        equ    $c229
EnterDeskTop        equ    $c22c
StartAppl        equ    $c22f
ExitTurbo        equ    $c232
PurgeTurbo        equ    $c235
DeleteFile        equ    $c238
FindFTypes        equ    $c23b
RstrAppl        equ    $c23e
ToBASIC         equ    $c241
FastDelFile        equ    $c244
GetDirHead        equ    $c247
PutDirHead        equ    $c24a
NxtBlkAlloc        equ    $c24d
ImprintRectangle    equ    $c250
i_ImprintRectangle    equ    $c253
DoDlgBox        equ    $c256
RenameFile        equ    $c259
InitForIO        equ    $c25c
DoneWithIO        equ    $c25f
DShiftRight        equ    $c262
CopyString        equ    $c265
CopyFString        equ    $c268
CmpString        equ    $c26b
CmpFString        equ    $c26e
FirstInit        equ    $c271
OpenRecordFile        equ    $c274
CloseRecordFile     equ    $c277
NextRecord        equ    $c27a
PreviousRecord        equ    $c27d
PointRecord        equ    $c280
DeleteRecord        equ    $c283
InsertRecord        equ    $c286
AppendRecord        equ    $c289
ReadRecord        equ    $c28c
WriteRecord        equ    $c28f
SetNextFree        equ    $c292
UpdateRecordFile    equ    $c295
GetPtrCurDkNm        equ    $c298
PromptOn        equ    $c29b
PromptOff        equ    $c29e
OpenDisk        equ    $c2a1
DoInlineReturn        equ    $c2a4
GetNextChar        equ    $c2a7
BitmapClip        equ    $c2aa
FindBAMBit        equ    $c2ad
SetDevice        equ    $c2b0
IsMseInRegion        equ    $c2b3
ReadByte        equ    $c2b6
FreeBlock        equ    $c2b9
ChangeDiskDevice    equ    $c2bc
RstrFrmDialogue     equ    $c2bf
Panic            equ    $c2c2
BitOtherClip        equ    $c2c5
StashRAM        equ    $c2c8
FetchRAM        equ    $c2cb
SwapRAM         equ    $c2ce
VerifyRAM        equ    $c2d1
DoRAMOp         equ    $c2d4
 
;only in GEOS 128
TempHideMouse        equ    $c2d7
SetMousePicture     equ    $c2da
SetNewMode        equ    $c2dd
NormalizeX        equ    $c2e0
MoveBData        equ    $c2e3
SwapBData        equ    $c2e6
VerifyBData        equ    $c2e9
DoBOp            equ    $c2ec
AccessCache        equ    $c2ef
HideOnlyMouse        equ    $c2f2
SetColorMode        equ    $c2f5
ColorCard        equ    $c2f8
ColorRectangle        equ    $c2fb